name       : liberation-circuit
version    : 1.3
release    : 2
source     :
    - https://github.com/linleyh/liberation-circuit/archive/v1.3.tar.gz : 3c18c5815aa139e2bf3048e42bbb4bf7f1b3d05022ea0a3c764bc25f420f2b4f
license    : GPL-3.0-only
component  : games.strategy
summary    : Trapped in a hostile computer system, you must make a way out - RTS/coding game
description: |
    Trapped in a hostile computer system, you must make a way out - RTS/coding game
builddeps  :
    - pkgconfig(allegro_main-5)
    - pkgconfig(gl)
    - redo
setup      : |
    %patch -p1 < $pkgfiles/0001-Set-a-default-savefile-location.patch
build      : |
    redo
install    : |
    install -Dm00755 $pkgfiles/libcirc $installdir/usr/bin/libcirc
    install -Dm00755 src/g_game $installdir/usr/share/libcirc/libcirc
    install -dm00777 $installdir/usr/share/libcirc/saves
    rm bin/libcirc*
    cp -R bin/* $installdir/usr/share/libcirc/
